name: caddy
networks:
  caddy:
    external: true
services:
  caddy:
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    image: homeall/caddy-reverse-proxy-cloudflare:latest
    labels:
      caddy.acme_dns: cloudflare $API_TOKEN
      caddy: http://router.praarthana.space
      caddy.reverse_proxy: http://192.168.1.1:80
      caddy_1: http://nas.praarthana.space
      caddy_1.reverse_proxy: http://192.168.1.2:8080
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/home/apps/caddy/data:/data
volumes:
  data: {}
