networks:
  caddy:
    external: true
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - /mnt/home/apps/caddy/data:/data
      - /mnt/home/apps/caddy/config:/config
    networks:
      - caddy
volumes:
  caddy_data:
  caddy_config:
