services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.praarthana.space"
      SIGNUPS_ALLOWED: "true" # TODO: remove after setup
    volumes:
      - /mnt/home/apps/vaultwarden/data:/data
    networks:
      - reverseproxy-nw
networks:
  reverseproxy-nw:
    external: true
