services:
  server:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    environment:
      - USER_UID=3002
      - USER_GID=3002
    restart: always
    labels:
      caddy: git.praarthana.space
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy
    volumes:
      - /mnt/home/apps/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  caddy:
    external: true
