name: immich
networks:
  caddy:
    external: true
services:
  immich-server:
    container_name: immich_server
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    image: ghcr.io/immich-app/immich-server:release
    extends:
      file: hwaccel.transcoding.yml
      service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    labels:
      caddy: photos.praarthana.space
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy
    restart: always
    volumes:
      - /mnt/home/apps/immich/data:/data
      - /etc/localtime:/etc/localtime:ro

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    healthcheck:
      disable: false
    image: ghcr.io/immich-app/immich-machine-learning:release
    extends:
      file: hwaccel.ml.yml
      service: cpu
    networks:
      - caddy
    restart: always
    volumes:
      - model-cache:/cache

  redis:
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    networks:
      - caddy
    restart: always

  database:
    container_name: immich_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    networks:
      - caddy
    restart: always
    shm_size: 128mb
    volumes:
      - /mnt/home/apps/immich/pgData:/var/lib/postgresql/data
volumes:
  model-cache:
